services:
  ebs:
    build: ebs
    restart: unless-stopped
    ports:
      - 8081:3000
    depends_on:
      - db
      - logger
    environment:
      HTTPS_METHOD: nohttps
      VIRTUAL_HOST: subnautica.vedal.ai
      MYSQL_HOST: db
      MYSQL_USER: ebs
      MYSQL_PASSWORD: ebs
      MYSQL_DATABASE: ebs
      LOGGER_HOST: logger

  logger:
    build: logger
    restart: unless-stopped
    ports:
      - 8082:3000
    depends_on:
      - db
    environment:
      HTTPS_METHOD: nohttps
      VIRTUAL_HOST: logger-subnautica.vedal.ai
      MYSQL_HOST: db
      MYSQL_USER: ebs
      MYSQL_PASSWORD: ebs
      MYSQL_DATABASE: ebs

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: ebs
      MYSQL_USER: ebs
      MYSQL_PASSWORD: ebs
    volumes:
      - ./_volumes/db:/var/lib/mysql
      - ./scripts/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.nginx-proxy.nginx
    environment:
      TRUST_DOWNSTREAM_PROXY: false
